### ISSUE TITLE
Project plan: Yuan Xinran, Stanley

### ISSUE THREAD

**Issue by SoilingRogue** [AY1920S1-CS2103T-T12-2/main#12]
Ordering features: Adding and summary of orders
- [x] v1.1: Add personal photo to AboutUs
- [x] v1.2: Implement order model, improve logic and parsing, and enable adding of order from customer side
- [ ] v1.3: Able to show summary of orders in the format: {customer} ordered {menu} from {restaurant}, {deliveryman} delivered to {location}
