### ISSUE TITLE
Project plan - Ee Ter

### ISSUE THREAD

**Issue by etlow** [AY1920S1-CS2103T-T12-2/main#13]
- [x] v1.1 Add photo to about us
- [x] v1.2 Undo of order related commands
- [ ] v1.3 Undo of another feature
