### ISSUE TITLE
Project Plan - Choong Jin Yao

### ISSUE THREAD

**Issue by charliechoong** [AY1920S1-CS2103T-T12-2/main#15]
- [x] v1.1 Add photo to About Us

- [x] v1.2 Implement Deliveryman class and related basic methods

- [ ] v1.3 Implement advanced methods for deliverymen and integrate into driver
